import { Nunito } from "next/font/google";
import "./globals.css";
import React from "react";

import Sidebar from "../components/Sidebar";
import GlobalStyleProvider from "./providers/GlobalStyleProvider";
import ContextProvider from "./providers/ContextProvider";

const nunito = Nunito({ 
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"] 
});

export const metadata = {
  title: "PlanAhead",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={nunito.className}>
        <ContextProvider>
          <GlobalStyleProvider>
            <Sidebar />
            <div className="w-full">{children}</div>
          </GlobalStyleProvider>
        </ContextProvider>
      </body>
    </html>
  );
}