remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: PlanAhead
description: aplikasi penjadwalan dengan AI untuk mempermudah manajemen waktu dan meningkatkan produktivitas.